name: Release Creation

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm ci
        npm run build

      # Install the FoundryVTT CLI.
    - run: npm install -g @foundryvtt/foundryvtt-cli 
      # Configure the datapath as the github workspace variable.
    - run: fvtt configure set "dataPath" ${GITHUB_WORKSPACE}
      # Package each folder of source json files into the appropriate LevelDB pack.
    - run: bash .github/pack.sh
    # get part of the tag after the `v`
    - name: Extract tag version number
      id: get_version
      uses: battila7/get-version-action@v2

    # Substitute the Manifest and Download URLs in the system.json
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: 'system.json'
      env:
        version: ${{steps.get_version.outputs.version-without-v}}
        url: https://github.com/${{github.repository}}
        manifest: https://github.com/${{github.repository}}/releases/latest/download/system.json
        download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/lhrpg-${{github.event.release.tag_name}}.zip

    # Create a zip file with all files required by the system to add to the release
    - run: zip -r ./lhrpg-${{github.event.release.tag_name}}.zip loghorizontrpg.mjs style.css system.json template.json LICENSE.txt lang/ packs/ templates/  --exclude="*packs/*/_source*"

    # Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # Set this to false if you want to prevent updating existing releases
        name: ${{ github.event.release.name }}
        draft: ${{ github.event.release.unpublished }}
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './system.json, ./lhrpg-${{github.event.release.tag_name}}.zip'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}
